ARG TAG="v1.0.0"
ARG UBI_IMAGE=registry.access.redhat.com/ubi7/ubi-minimal:latest
ARG GO_IMAGE=goboring/golang:1.15.8b5

# Build the project
FROM ${GO_IMAGE} as builder
ARG TAG
COPY 0002-Allow-adding-GOFLAGS.patch .
ENV GOFLAGS=-trimpath
RUN apt update && apt -y install patch
RUN git clone https://github.com/k8snetworkplumbingwg/sriov-network-operator \
    && cd sriov-network-operator \
    && git fetch --all --tags --prune \
    && git checkout ${TAG} -b ${TAG} \
    && patch -p1 < ../0002-Allow-adding-GOFLAGS.patch \
    && make clean && make _build-sriov-network-config-daemon \
    && make plugins

# Create the sriov-cni image
FROM ${UBI_IMAGE}
WORKDIR /
COPY centos.repo /etc/yum.repos.d/centos.repo
RUN microdnf update -y && ARCH_DEP_PKGS=$(if [ "$(uname -m)" != "s390x" ]; then echo -n mstflint ; fi) && \
    microdnf install hwdata $ARCH_DEP_PKGS
COPY --from=builder /go/sriov-network-operator/build/_output/linux/amd64/sriov-network-config-daemon /usr/bin/
COPY --from=builder /go/sriov-network-operator/build/_output/linux/amd64/plugins /plugins
COPY --from=builder /go/sriov-network-operator/bindata /bindata
ENV PLUGINSPATH=/plugins
ENTRYPOINT ["/usr/bin/sriov-network-config-daemon"]
