ARG TAG="release-4.8"
ARG UBI_IMAGE=registry.access.redhat.com/ubi7/ubi-minimal:latest
ARG GO_IMAGE=goboring/golang:1.15.8b5

# Build the project
FROM ${GO_IMAGE} as builder
ARG TAG
RUN apt update && apt -y install patch
RUN git clone https://github.com/k8snetworkplumbingwg/sriov-network-operator
WORKDIR sriov-network-operator
RUN git fetch --all --tags --prune
RUN git branch -a
RUN git checkout remotes/origin/${TAG} -b ${TAG}
COPY 0003-Allow-adding-GOFLAGS.patch 0002-Change-the-module-URL-from-openshift-to-k8snetworkpl.patch ./
RUN patch -p1 < 0002-Change-the-module-URL-from-openshift-to-k8snetworkpl.patch
RUN patch -p1 < 0003-Allow-adding-GOFLAGS.patch
ENV GOFLAGS=-trimpath
RUN make clean && make _build-sriov-network-config-daemon
RUN make plugins

# Create the sriov-cni image
FROM ${UBI_IMAGE}
WORKDIR /
COPY centos.repo /etc/yum.repos.d/centos.repo
RUN microdnf update -y && ARCH_DEP_PKGS=$(if [ "$(uname -m)" != "s390x" ]; then echo -n mstflint ; fi) && \
    microdnf install hwdata $ARCH_DEP_PKGS
COPY --from=builder /go/sriov-network-operator/build/_output/linux/amd64/sriov-network-config-daemon /usr/bin/
COPY --from=builder /go/sriov-network-operator/build/_output/linux/amd64/plugins /plugins
COPY --from=builder /go/sriov-network-operator/bindata /bindata
ENV PLUGINSPATH=/plugins
ENTRYPOINT ["/usr/bin/sriov-network-config-daemon"]
